version: "3.3"

networks:
  database:

services:
  db:
    container_name: db
    image: postgres
    restart: always
    networks:
      - database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ponto
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    build: ./api
    restart: always
    networks:
      - database
    ports:
      - "4200:4200"
    depends_on:
      - db
    environment:
      - API_PORT=4200
      - DB_CONNECTION=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=ponto
      - DB_USERNAME=user
      - DB_PASSWORD=password

  client:
    build: ./app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  dbdata:
