version: "1"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=mydatabase
      - PGPASSWORD=mysecretpassword
      - PGPORT=5432
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
